### ISSUE TITLE
Continuity between different curves and lofts

### ISSUE THREAD

**Issue by kkpal3** [szb5100/BB3D#1]
Hi Stephen, thank you for sharing the code! As far as I understand, this code builds the blade first by constructing the top and bottom curves of each airfoil sections, and then creating several lofts to combine them.

I'm wondering is there any continuity constraints enforced between the top and bottom curves, as well as between different lofts?

**Comment by szb5100** [comment]
Hi Kai,
You are correct. The blade is constructed by first generating the 2-dimensional span sections and then lofts are created between them separately on the top and bottom surfaces. The lofts are tangency constrained between the span sections, but only position constrained at the leading and trailing edge. The spanwise sections are just b-spline interpolations through points, and I did not impose any tangency constraint at that location; after visual inspection I did not think it was a big deal. The resolution in the airfoil shape files was adequate to get good surface continuity there without any extra treatment. If this isn't sufficient for your purposes though, I could help you make that update to the code; it's not difficult. There is a thin surface at the trailing edge providing a very small thickness, so no tangency condition is necessary there.

**Comment by kkpal3** [comment]
Dear Stephen, thank you for your reply! Now I understand your code better. I can see a significant part of your code is dedicated to the connecting part between different loft.

I think it would be perfect if the tangency at the leading edge is also enforced (so that no one can be picky about the code). To achieve this, what I'm thinking now is to construct the airfoil use only one spline. I modified your code a bit to generate the following:

![Capture](https://user-images.githubusercontent.com/50759466/102274684-4543a180-3ef2-11eb-81cf-f553d38579ff.JPG)

It seems that with only one spline for the whole airfoil section, I can not use a lot of sections in one loft (throws out a "std::bad_array_new_length" error), so I've divided the blade into 4 lofts. I'm still trying to understand the part of code for connecting lofts. Do you think it's a feasible way to do it? or do you have better methods to achieve tangency at leading edge?

**Comment by szb5100** [comment]
Kai, the reason I interpolate the curve in two sections (top and bottom) is because I found that method to give the best representation of the airfoil section. Interpolating the whole curve is difficult to do within a reasonable tolerance because of the high curvature at the leading edge. If you can cluster bspline poles near the leading edge, then maybe you can still get a good tolerance, but I opted to perform the interpolation in two passes because it is simpler and also always results in a smooth isoline along the leading edge which is helpful for mesh generation. If the method you are showing above is not affected by the above issue, then it might very well be a valid solution worth implementing.

I just committed an update to the code which fixes the tangency condition at the leading edge by altering the adjacent bspline pole from the leading edge on both the upper and lower curves prior to the lofts. The surface generation still does not have a tangency constraint, but since the curves which are being lofted have tangency this should implicitly enforce the tangency of the surfaces as well, at least within a very small tolerance. If this update solves your problem then let me know and I will close the issue.

**Comment by kkpal3** [comment]
Thank you Stephen for the update. This solves my problem.
